config/routes.rb
Catarse::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :passwords => "passwords"}

  ActiveAdmin.routes(self)

  filter :locale

  root :to => "projects#index"
  match "/reports/financial/:project_id/backers" => "reports#financial_by_project", :as => :backers_financial_report
  match "/reports/location/:project_id/backers" => "reports#location_by_project", :as => :backers_location_report
  match "/reports/users_most_backed" => "reports#users_most_backed", :as => :most_backed_report

  match '/sitemap' => "static#sitemap", :as => :sitemap
  # Static Pages
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/faq" => "static#faq", :as => :faq
  match "/terms" => "static#terms", :as => :terms
  match "/privacy" => "static#privacy", :as => :privacy

  match "/thank_you" => "payment_stream#thank_you", :as => :thank_you
  match "/moip" => "payment_stream#moip", :as => :moip
  match "/explore" => "explore#index", :as => :explore
  match "/explore/:quick" => "explore#index", :as => :explore_quick
  post '/explore/update_attribute_on_the_spot' => "explore#update_attribute_on_the_spot"
  match "/credits" => "credits#index", :as => :credits

  post "/auth" => "sessions#auth", :as => :auth
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout
  if Rails.env == "test"
    match "/fake_login" => "sessions#fake_create", :as => :fake_login
  end
  resources :projects, :only => [:index, :new, :create, :show] do
    resources :rewards
    resources :backers, :controller => 'projects/backers' do
      collection do
        post 'review'
      end
      member do
        put 'checkout'
      end
    end
    collection do
      get 'start'
      post 'send_mail'
      get 'vimeo'
      get 'cep'
      get 'pending'
      get 'pending_backers'
      get 'thank_you'
      post 'update_attribute_on_the_spot'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'comments'
      get 'updates'
    end
  end
  resources :users, :only => [:show] do
    post 'update_attribute_on_the_spot', :on => :collection
  end
  resources :credits, :only => [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end
  resources :comments, :only => [:index, :show, :create, :destroy]

  resources :paypal, :only => [] do
    member do
      get 'pay'
      get 'success'
      get 'cancel'
    end
  end

  resources :curated_pages do
    collection do
      post 'update_attribute_on_the_spot'
    end
  end
  match "/:permalink" => "curated_pages#show", :as => :curated_page
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :new
  before_filter :load_project

  def index
    @backers = @project.backers.confirmed.order("confirmed_at DESC").paginate :page => params[:page], :per_page => 10
    render :json => @backers.to_json(:can_manage => can?(:manage, @project))
  end

  def new
    return unless require_login
    unless @project.can_back?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end
    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def review
    return unless require_login

    @title = t('projects.backers.review.title')
    params[:backer][:reward_id] = nil if params[:backer][:reward_id] == '0'
    params[:backer][:user_id] = current_user.id
    @project = Project.find params[:project_id]
    @backer = @project.backers.new(params[:backer])

    unless @backer.save
      flash[:failure] = t('projects.backers.review.error')
      return redirect_to new_project_backer_path(@project)
    end

    session[:thank_you_id] = @project.id
  end

  def checkout
    return unless require_login

    backer = current_user.backs.find params[:id]
    if backer.credits
      if current_user.credits < backer.value
        flash[:failure] = t('projects.backers.checkout.no_credits')
        return redirect_to new_project_backer_path(backer.project)
      end
      unless backer.confirmed
        current_user.update_attribute :credits, current_user.credits - backer.value
        backer.update_attribute :payment_method, 'Credits'
        backer.confirm!
      end
      flash[:success] = t('projects.backers.checkout.success')
      redirect_to thank_you_path
    else
      begin
        current_user.update_attributes params[:user]
        current_user.reload
        payer = {
          :nome => current_user.full_name,
          :email => current_user.email,
          :logradouro => current_user.address_street,
          :numero => current_user.address_number,
          :complemento => current_user.address_complement,
          :bairro => current_user.address_neighbourhood,
          :cidade => current_user.address_city,
          :estado => current_user.address_state,
          :pais => "BRA",
          :cep => current_user.address_zip_code,
          :tel_fixo => current_user.phone_number
        }
        payment = {
          :valor => "%0.0f" % (backer.value),
          :id_proprio => backer.key,
          :razao => "Apoio para o projeto '#{backer.project.name}'",
          :forma => "BoletoBancario",
          :dias_expiracao => 2,
          :pagador => payer,
          :url_retorno => thank_you_url
        }
        response = MoIP::Client.checkout(payment)
        backer.update_attribute :payment_token, response["Token"]
        session[:_payment_token] = response["Token"]
        redirect_to MoIP::Client.moip_page(response["Token"])
      rescue
        flash[:failure] = t('projects.backers.checkout.moip_error')
        return redirect_to new_project_backer_path(backer.project)
      end
    end
  end



  private

  def load_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper
  inherit_resources
  actions :index, :show, :new, :create
  respond_to :html, :except => [:backers, :comments, :updates]
  respond_to :json, :only => [:show, :backers, :comments, :updates]
  can_edit_on_the_spot
  skip_before_filter :detect_locale, :only => [:backers, :comments, :updates]
  before_filter :can_update_on_the_spot?, :only => :update_attribute_on_the_spot
  before_filter :date_format_convert, :only => [:create]
  def date_format_convert
    # TODO localize here and on the datepicker on project_form.js
    params["project"]["expires_at"] = Date.strptime(params["project"]["expires_at"], '%d/%m/%Y')
  end

  def index
    index! do
      @title = t("site.title")
      @home_page = Project.includes(:user, :category).visible.home_page.limit(6).order('"order"').all
      @expiring = Project.includes(:user, :category).visible.expiring.not_home_page.not_expired.order('expires_at, created_at DESC').limit(3).all
      @recent = Project.includes(:user, :category).visible.not_home_page.not_expiring.not_expired.where("projects.user_id <> 7329").order('created_at DESC').limit(3).all
      @successful = Project.includes(:user, :category).visible.not_home_page.successful.order('expires_at DESC').limit(3).all
      @curated_pages = CuratedPage.visible.order("created_at desc").limit(6)
    end
  end
  def start
    @title = t('projects.start.title')
  end
  def send_mail
    current_user.update_attribute :email, params[:contact] if current_user.email.nil?
    ProjectsMailer.start_project_email(params[:about], params[:rewards], params[:links], params[:contact], current_user, "#{I18n.t('site.base_url')}#{user_path(current_user)}").deliver
    flash[:success] = t('projects.send_mail.success')
    redirect_to :root
  end
  def new
    return unless require_login
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end
  def create
    params[:project][:expires_at] += (23.hours + 59.minutes + 59.seconds) if params[:project][:expires_at]
    validate_rewards_attributes if params[:project][:rewards_attributes].present?
    create!(:notice => t('projects.create.success'))
    # When it can't create the project the @project doesn't exist and then it causes a record not found
    # because @project.reload *works only with created records*
    unless @project.new_record?
      @project.reload
      @project.update_attribute :short_url, bitly
    end
  end
  def show
    show!{
      @title = @project.name
      @rewards = @project.rewards.order(:minimum_value).all
      @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
      @updates = @project.updates.all
      @update = @project.comments.new :project_update => true
      @comments = @project.comments.all
      @comment = @project.comments.new
    }
  end
  def vimeo
    project = Project.new(:video_url => params[:url])
    if project.vimeo
      render :json => project.vimeo.to_json
    else
      render :json => {:id => false}.to_json
    end
  end
  def cep
    address = BuscaEndereco.por_cep(params[:cep])
    render :json => {
      :ok => true,
      :street => "#{address[0]} #{address[1]}",
      :neighbourhood => address[2],
      :state => address[3],
      :city => address[4]
    }.to_json
  rescue
    render :json => {:ok => false}.to_json
  end

  def comments
    @project = Project.find params[:id]
    @comments = @project.comments.order("created_at DESC").paginate :page => params[:page], :per_page => 5
    respond_with @comments
  end

  def updates
    @project = Project.find params[:id]
    @updates = @project.updates.order("created_at DESC").paginate :page => params[:page], :per_page => 3
    respond_with @updates
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def pending
    return unless require_admin
    @title = t('projects.pending.title')
    @search = Project.search(params[:search])
    @projects = @search.order('projects.created_at DESC').paginate :page => params[:page]
  end
  def pending_backers
    return unless require_admin
    @title = t('projects.pending_backers.title')
    @search = Backer.search(params[:search])
    @backers = @search.order("created_at DESC").paginate :page => params[:page]
    @total_backers = User.backers.count
    @total_backs = Backer.confirmed.count
    @total_backed = Backer.confirmed.sum(:value)
    @total_users = User.primary.count
  end
  private

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end

  def bitly
    return unless Rails.env.production?
    require 'net/http'
    res = Net::HTTP.start("api.bit.ly", 80) { |http| http.get("/v3/shorten?login=diogob&apiKey=R_76ee3ab860d76d0d1c1c8e9cc5485ca1&longUrl=#{CGI.escape(project_url(@project))}") }
    data = JSON.parse(res.body)['data']
    data['url'] if data
  end
  def can_update_on_the_spot?
    project_fields = []
    project_admin_fields = ["name", "about", "headline", "can_finish", "expires_at", "user_id", "image_url", "video_url", "visible", "rejected", "recommended", "home_page", "order"]
    backer_fields = ["display_notice"]
    backer_admin_fields = ["confirmed", "requested_refund", "refunded", "anonymous", "user_id"]
    reward_fields = []
    reward_admin_fields = ["description"]
    def render_error; render :text => t('require_permission'), :status => 422; end
    return render_error unless current_user
    klass, field, id = params[:id].split('__')
    return render_error unless klass == 'project' or klass == 'backer' or klass == 'reward'
    if klass == 'project'
      return render_error unless project_fields.include?(field) or (current_user.admin and project_admin_fields.include?(field))
      project = Project.find id
      return render_error unless current_user.id == project.user.id or current_user.admin
    elsif klass == 'backer'
      return render_error unless backer_fields.include?(field) or (current_user.admin and backer_admin_fields.include?(field))
      backer = Backer.find id
      return render_error unless current_user.admin or (backer.user == current_user)
    elsif klass == 'reward'
      return render_error unless reward_fields.include?(field) or (current_user.admin and reward_admin_fields.include?(field))
      reward = Reward.find id
      return render_error unless current_user.admin
    end
  end
end

app/views/projects/_about.html.slim
script type="text/template" id="project_about_template"
  #project_about
    - if current_user and current_user.admin
      #{on_the_spot_edit @project, :about, :type => :textarea}
    - else
      == @project.about_html
    = render "admin_fields" if current_user and current_user.admin

app/views/projects/_back_info.html.slim
#project_back_info
  #back_project= render :partial => 'back_project'
  #rewards= render :partial => 'rewards'
.clear

app/views/projects/_back_project.html.haml
.info
  .number= @project.total_backers
  #{pluralize_without_number(@project.total_backers, t('.person'))} #{t('.has')} #{pluralize_without_number(@project.total_backers, t('.backed_singular'), t('.backed_plural'))}
  .number= @project.display_pledged
  = t('.reached_of')
  %strong= @project.display_goal
  #time_to_go.number= @project.time_to_go[:time]
  #{@project.time_to_go[:unit].capitalize} #{pluralize_without_number(@project.time_to_go[:time], t('remaining_singular'), t('remaining_plural'))}
  .project_progress
    .progress_bar
      .progress{ :style => "width: #{ @project.display_percent }%" }
        &nbsp;
- if @project.successful?
  .project_warning.successful
    .text
      - if @project.expired?
        = t('.project_warning.successful.expired', :date => @project.display_expires_at)
      - else
        = t('.project_warning.successful.not_expired', :date => @project.display_expires_at)
- elsif @project.waiting_confirmation?
  .project_warning.waiting_confirmation
    .text= t('.project_warning.waiting_confirmation')
- else
  .project_warning.not_successful
    .text
      - if @project.expired?
        = t('.project_warning.not_successful.expired', :goal => @project.display_goal, :date => @project.display_expires_at)
      - else
        = t('.project_warning.not_successful.not_expired', :goal => @project.display_goal, :date => @project.display_expires_at)
.info
  = form_tag(new_project_backer_path(@project), :method => :get, :id => 'back_project_form') do
    %fieldset
      = submit_tag t('.submit'), :disabled => (not @project.can_back?)

app/views/projects/_embed.html.haml
- style = "-moz-border-radius: 8px;-webkit-border-radius: 8px;-o-border-radius: 8px;-ms-border-radius: 8px;-khtml-border-radius: 8px;border-radius: 8px;-moz-box-shadow: rgba(0, 0, 0, 0.5) 5px 5px 10px 0;-webkit-box-shadow: rgba(0, 0, 0, 0.5) 5px 5px 10px 0;-o-box-shadow: rgba(0, 0, 0, 0.5) 5px 5px 10px 0;box-shadow: rgba(0, 0, 0, 0.5) 5px 5px 10px 0;"
#embed_overlay.overlay.hide
  #project_embed.hide
    %a.close{ :href => '#' } X
    #project_box_embed
      %iframe{ :frameborder => '0', :height => '388px', :width => '264px', :src => embed_project_path(@project)}
      %form.html= text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="388px" src="' + embed_project_url(@project) + '" width="264px" style="' + style + '"></iframe>', :readonly => true
    #project_video_embed
      %iframe{ :frameborder => '0', :height => '388px', :width => '364px', :src => video_embed_project_path(@project)}
      %form.html= text_area_tag 'project_video_embed_html', '<iframe frameborder="0" height="388px" src="' + video_embed_project_url(@project) + '" width="364px" style="' + style + '"></iframe>', :readonly => true
    .clear
= javascript_include_tag 'project_embed'

app/views/projects/_home_page_projects.html.haml
- unless @home_page.empty?
  .project_list_header= t(".title")
  .project_list_subheader= t(".subtitle")
  #home_page_projects
    = render :partial => 'project', :collection => @home_page
    .clear
  .explore_more
    %hr
    = link_to explore_quick_path("recommended") do
      = t('.explore_recommended')
      .explore_more_arrow >

app/views/projects/_index_meta_tags.html.haml
= content_for :meta_tags do
  %meta{:name => "description", :content => t('.description')}
  -# Meta tags for facebook social graph
  %meta{:property => "og:title", :content => "#{@title}#{' · ' if @title}#{t('site.name')}"}
  %meta{:property => "og:type", :content => 'cause'}
  %meta{:property => "og:url", :content => root_url}
  %meta{:property => "og:image", :content => "#{t('site.base_url')}/images/home_small.png"}
  %meta{:property => "og:site_name", :content => t('site.name')}
  %meta{:property => "og:description", :content => t('.description')}

app/views/projects/_project_list.html.haml
%br
- if defined?(quick)
  .project_list_header= t(".#{quick}.title")
  .project_list_subheader= t(".#{quick}.subtitle")
.project_list_wrapper
  .project_list
    = render :partial => 'projects/project', :collection => collection
- if defined?(quick)
  .explore_more
    %hr
    = link_to explore_quick_path(quick) do
      = t(".#{quick}.explore")
      .explore_more_arrow >

app/views/projects/_project_meta_tags.html.haml
= content_for :meta_tags do
  %meta{:name => "description", :content => @project.headline}
  -# Meta tags for facebook social graph
  %meta{:property => "og:title", :content => @project.name}
  %meta{:property => "og:type", :content => 'cause'}
  %meta{:property => "og:url", :content => "#{t('site.base_url')}#{project_path(@project)}"}
  %meta{:property => "og:image", :content => @project.display_image}
  %meta{:property => "og:site_name", :content => t('site.name')}
  %meta{:property => "og:description", :content => @project.headline}
  %meta{:property => "fb:admins", :content => "567237711"}

app/views/projects/_project_updates.html.slim
script type="text/template" id="project_updates_template"
  #empty_template.hide= t('.empty')
  #project_updates
    -if current_user and @project.user == current_user
      = semantic_form_for @update, :html => { :id => 'new_update_form' } do |form|
        = form.inputs do
          = form.input :commentable_type, :as => :hidden, :required => false
          = form.input :commentable_id, :as => :hidden, :required => false
          = form.input :project_update, :as => :hidden, :required => false
          = form.input :title, :label => t('.title'), :as => :string, :required => true
          = form.input :comment, :label => t('.text'), :as => :text, :required => true
        = render :partial => 'formatting_tips'
        = form.buttons do
          = form.commit_button t('.submit')
    ul#collection_list

app/views/projects/embed.html.haml
#embed
  = render :partial => 'project', :locals => { :project => @project }
= javascript_include_tag 'embed'

app/views/projects/index.html.haml
= render :partial => "index_header"
= render :partial => "index_meta_tags"
= render 'home_page_projects'
= render :partial => 'project_list', :locals => {:quick => "expiring", :collection => @expiring} unless @expiring.empty?
= render :partial => 'project_list', :locals => {:quick => "recent", :collection => @recent} unless @recent.empty?
= render :partial => 'project_list', :locals => {:quick => "successful", :collection => @successful} unless @successful.empty?
= render :partial => 'curated_pages_list', :locals => {:curated_pages => @curated_pages} unless @curated_pages.empty?
.clear
= render :partial => "press"
= javascript_include_tag 'press'
= javascript_include_tag 'root'

app/views/projects/pending.html.haml
= content_for :content_header do
  %h1= t('.title')
#pending_projects
  = form_for @search, :url => pending_projects_path do |f|
    %fieldset
      = f.label :id_equals, t('.id')
      = f.text_field :id_equals
      = f.label :name_contains, t('.name')
      = f.text_field :name_contains
      = f.label :user_name_contains, t('.user')
      = f.text_field :user_name_contains
      = f.check_box :visible_is_true
      = f.label :visible_is_true, t('.visible')
      = f.check_box :rejected_is_true
      = f.label :rejected_is_true, t('.rejected')
    %fieldset
      = f.check_box :recommended_is_true
      = f.label :recommended_is_true, t('.recommended')
      = f.check_box :home_page_is_true
      = f.label :home_page_is_true, t('.home_page')
      = f.check_box :can_finish_is_true
      = f.label :can_finish_is_true, t('.can_finish')
      = f.check_box :finished_is_true
      = f.label :finished_is_true, t('.finished')
      = f.submit t('.submit')
  #total_results
    = pluralize_without_number @search.count, t('found_singular'), t('found_plural')
    %strong= @search.count
    = pluralize_without_number @search.count, t('activerecord.models.project').downcase
  = will_paginate @projects
  .clear
  - if @projects.empty?
    = t('.no_projects')
  - else
    %table
      %thead
        %tr
          %th= t('.id')
          %th= t('.project')
          %th= t('.user')
          %th= t('.visible')
          %th= t('.rejected')
          %th= t('.recommended')
          %th= t('.home_page')
          %th= t('.order')
          %th= t('.can_finish')
          %th= t('.finished')
      %tbody
        - @projects.each do |project|
          %tr{ :class => cycle("even", "odd") }
            %td= project.id
            %td{ :title => project.name }
              = link_to project_path(project) do
                = image_tag project.display_image
            %td{ :title => project.user.display_name }
              = link_to user_path(project.user) do
                = image_tag project.user.display_image
            %td= check_box_tag "project__visible__#{project.id}", '1', project.visible
            %td= check_box_tag "project__rejected__#{project.id}", '1', project.rejected
            %td= check_box_tag "project__recommended__#{project.id}", '1', project.recommended
            %td= check_box_tag "project__home_page__#{project.id}", '1', project.home_page
            %td= on_the_spot_edit project, :order, :tooltip => '-'
            %td= check_box_tag "project__can_finish__#{project.id}", '1', project.can_finish
            %td= (project.finished ? t('yes') : t('no'))
  = will_paginate @projects
= javascript_include_tag 'pending_projects'

app/views/projects/pending_backers.html.haml
= content_for :content_header do
  %h1= t('.title')
  %h2
    %strong= @total_backers
    = t('.total_backers')
    ·
    %strong= @total_backs
    = t('.total_backs')
    ·
    %strong= number_to_currency @total_backed, :unit => 'R$', :precision => 0, :delimiter => '.'
    = t('.total_backed')
    ·
    %strong= @total_users
    = t('.total_users')
#pending_backers
  = form_for @search, :url => pending_backers_projects_path do |f|
    %fieldset
      = f.label :id_equals, t('.id')
      = f.text_field :id_equals
      = f.label :key_equals, t('.key')
      = f.text_field :key_equals
      = f.label :project_name_contains, t('.project')
      = f.text_field :project_name_contains
      = f.label :user_name_contains, t('.user')
      = f.text_field :user_name_contains
    %fieldset
      = f.check_box :confirmed_is_true
      = f.label :confirmed_is_true, t('.confirmed')
      = f.check_box :credits_is_true
      = f.label :credits_is_true, t('.credits')
      = f.check_box :requested_refund_is_true
      = f.label :requested_refund_is_true, t('.requested_refund')
      = f.check_box :refunded_is_true
      = f.label :refunded_is_true, t('.refunded')
      = f.submit t('.submit')
  #total_results
    = pluralize_without_number @search.count, t('found_singular'), t('found_plural')
    %strong= @search.count
    = pluralize_without_number(@search.count, t('backer_singular'), t('backer_plural')).downcase
  = will_paginate @backers
  - if @backers.empty?
    = t('.no_backers')
  - else
    %table
      %thead
        %tr
          %th= t('.id')
          %th= t('.project')
          %th= t('.user')
          %th= t('.value')
          %th= t('.reward')
          %th= t('.key')
          %th= t('.confirmed')
          %th= t('.anonymous')
          %th= t('.credits')
          %th= t('.requested_refund')
          %th= t('.refunded')
      %tbody
        - @backers.each do |backer|
          %tr{ :id => backer.id, :class => cycle("even", "odd") }
            %td= backer.id
            %td{ :title => backer.project.name }
              = link_to project_path(backer.project) do
                = image_tag backer.project.display_image
            %td{ :title => backer.user.display_name }
              = link_to user_path(backer.user) do
                = image_tag backer.user.display_image
              .user_id= on_the_spot_edit backer, :user_id
            %td= backer.display_value
            %td{ :title => ("#{backer.reward.display_minimum} - #{backer.reward.description}" if backer.reward) }
              - if backer.reward
                = backer.reward.display_minimum
              - else
                \-
            %td.key= backer.key
            %td= check_box_tag "confirmed__#{backer.id}", '1', backer.confirmed
            %td= check_box_tag "anonymous__#{backer.id}", '1', backer.anonymous
            %td= (backer.credits ? t('yes') : t('no'))
            %td= (backer.requested_refund ? t('yes') : t('no'))
            %td= check_box_tag "refunded__#{backer.id}", '1', backer.refunded
  = will_paginate @backers
= javascript_include_tag 'pending_backers'

app/views/projects/show.html.haml
= render 'project_header'
= render 'project_meta_tags'
= render 'project_warning'
#project_description
  #project_video
    %iframe{:src => "#{@project.video_embed_url}?title=0&amp;byline=0&amp;portrait=0&amp", :width => "610", :height => "346"}
    #project_share
      #facebook_share= render 'facebook'
      #twitter_share= render 'twitter'
      %ul
        %li.link
          = image_tag "link_share.png", :title => t('.share.link_title')
          = t('.share.link')
          = text_field_tag "project_link", @project.short_url
        %li.embed
          = link_to '#', :id => 'embed_link' do
            = image_tag "embed_share.png", :title => t('.share.embed_title')
            = t('.share.embed')
      .clear
    = render 'embed'
  #project_menu
    %ul
      %li
        = link_to '#about', :id => 'about_link' do
          = t('.menu.about')
          = image_tag "project_menu_selected.png"
      %li
        = link_to '#updates', :id => 'updates_link' do
          = t('.menu.updates')
          %span.count (#{@updates.count})
          = image_tag "project_menu_selected.png"
      %li
        = link_to '#backers', :id => 'backers_link' do
          = t('.menu.backers')
          %span.count (#{@project.total_backers})
          = image_tag "project_menu_selected.png"
      %li
        = link_to '#comments', :id => 'comments_link' do
          = t('.menu.comments')
          %span.count (#{@comments.count})
          = image_tag "project_menu_selected.png"
  #project_content
  #loading= image_tag "loading.gif"
= render :partial => 'back_info'
= render :partial => 'about'
= render :partial => 'project_backers'
= render :partial => 'backer'
= render :partial => 'project_comments'
= render :partial => 'comment'
= render :partial => 'project_updates'
= render :partial => 'update'
= render :partial => 'error'
= javascript_include_tag 'models/project'
= javascript_include_tag 'models/user'
= javascript_include_tag 'models/paginated_collection'
= javascript_include_tag 'models/project_collection'
= javascript_include_tag 'models/backer'
= javascript_include_tag 'models/comment'
= javascript_include_tag 'models/update'
= javascript_include_tag 'controllers/project'
= javascript_include_tag 'views/project/content'
= javascript_include_tag 'views/project/model'
= javascript_include_tag 'views/project/paginated_content'
= javascript_include_tag 'views/project/about'
= javascript_include_tag 'views/project/backer'
= javascript_include_tag 'views/project/project_backers'
= javascript_include_tag 'views/project/comment'
= javascript_include_tag 'views/project/project_comments'
= javascript_include_tag 'views/project/update'
= javascript_include_tag 'views/project/project_updates'
= javascript_include_tag 'show_project'
:javascript
  var project = new Project(#{@project.to_json})
  var currentUser = new User(#{current_user.to_json})
  var projectController = new ProjectController({project: project})
  Backbone.history.start()